### PR TITLE
Fix: Verify Email Page Text Layout #66

### PR DESCRIPTION
**Pull request by EkaterinaEg**
## Requirements
- Text and styling should match the text in Figma
- Use svg for the icon
- Confirm the number of times user can use resend verification link
- Be creative with the coding solutions :)

## Notes
Responsiveness is not in the scope of this ticket.

## Test Steps
1. Open the application.
2. Go to Register page (Sign up)
3. Register
4. Check Sign up page according to figma (resend link is disable for 2 minutes)
5. Wait 2 minutes and click "Resend verification link" )
6. Check Modal window according to figma 
7. Close Modal window. Resend link is not available any more.
8. In case of any errors check Error page (no design)

## UI/UX Outcome
- link is disable
Screenshot 2024-08-12 153600
- link is enable
Screenshot 2024-08-12 153824
- modal window
Screenshot 2024-08-12 153836
- modal window is closed
Screenshot 2024-08-01 145451
- Error page
Screenshot 2024-08-12 150541

## Checklist
- [X] Pull Request title includes the issue number and a brief description of the change.
- [X] All changes should be tested and verified to work correctly.
- [X] Code follows frontend best practices.
- [X] Branch names follow the conventions in the contributing file.
- [X] Commit messages follow the naming conventions in the contributing file.

### CODE REVIEW

**Review by S-chahine — APPROVED** [review]
Great Job!

**Comment by ElenaCherpakova** [comment]
@EkaterinaEg I tested your branch on front with `dev` on back and here are some issues Im facing:

Screen Shot 2024-08-12 at 7 58 47 PM

And if I activate my account the `next` button is still disabled for me
Screen Shot 2024-08-12 at 7 58 59 PM

**Comment by EkaterinaEg** [comment]
Elena, 
Thank you for time. 

I was working on sending e-mail verification page component. It is supposed that you have not received verification email and wait 2 minutes to resend it second time (in my case it is not supposed to be verified). All errors go from Activate account component after email verified. I didn't check Activate component in this PR. I guess this block of 3 pages with different scenarios.  
Screenshot 2024-08-12 212114

**Comment by AnnaSolovykh** [comment]
> Elena, 
> 
> Thank you for time. 
> 
> 
> 
> I was working on sending e-mail verification page component. It is supposed that you have not received verification email and wait 2 minutes to resend it second time (in my case it is not supposed to be verified). All errors go from Activate account component after email verified. I didn't check Activate component in this PR. I guess this block of 3 pages with different scenarios.  
> 
> Screenshot 2024-08-12 212114
> 
> 

Hi Kate!
If some feature is merged into dev, that means it is checked and works properly. If smth is broken in dev, hot fix follows right away. 
If smth stops working properly in your PR, you should fix it as it is connected with the code you have added. We cannot approve the PR if smth misfunctions there as it will break our dev branch. 
Thank you for your understanding.

**Comment by ElenaCherpakova** [comment]
I digged into it and yes, since you removed `useNavigation` next button is no longer working. You are accepting `isActive` and `isLoading` as props in `NotificationPage` component for success condition you need to pass them as well and correct `handleClick` function in that case

**Comment by EkaterinaEg** [comment]
Dear colleagues,
I fixed errors: 
1) Changed my logic and added conditional rendering in EmailVerify Component.
2) Delete Error Page (instead I use conditional rendering in case if errors)
3) in Activate component I added state IsButton(false) to use NavLink (NotificationPage component) to navigate to Next, Sign up, Home ...

Please test it and let me know if you see any problems/concerns. Thank you!

**Review by ElenaCherpakova — APPROVED** [review]

**Pull request merged**
