### PR TITLE
Feat: Edit kid's profile 

### PR DESCRIPTION
**Pull request by Judithlourde**
One Line Description
Implemented Edit Kid's Profile feature, enabling users to edit profiles.

Requirements
- Modify the KidForm component to support both "add" and "edit" modes.
- Follow the design provided in Figma.
- Connect frontend with the backend API for updating kid profiles.

Notes
- The frontend implementation connects to the backend API for editing and deleting kids' profiles.
- Please ensure the backend branch [fix/99/edit-kids-profile](https://github.com/JULIERAJ/KIDS-FIRST-Back/tree/fix/99/edit-kids-profile) in the [KIDS-FIRST-Back repository] is used for testing.

Test Steps
- Navigate to the kid's profile page in the app.
- Click "Edit" on an existing kid's profile to load the KidForm in edit mode.
- Modify fields and save to update the profile.
- Verify successful updates in the database.
- Test adding a new kid profile in "add" mode.
- Ensure the backend branch is checked out and running during testing [fix/99/edit-kids-profile].

UI/UX Outcome
image

Checklist
- [x] Pull Request title includes the issue number and a brief description of the change.
- [x] All changes should be tested and verified to work correctly.
- [x] Code follows frontend best practices.
- [x] Branch names follow the conventions in the contributing file.
- [x] Commit messages follow the naming conventions in the contributing file.

### CODE REVIEW

**Comment by swathivt** [comment]
Hi Judith You have done a great job. but there are few small errors 
1. Can you make the cursor appear on the 'Edit' button when hovering over it?
2. There is no space between the values after editing the kid's form.
image
3. When I edit the kid's form for the first time, the values changed. However, when I try to edit it again for the second time, the information from the first edit does not appear. It shows like this
image

**Review by pandjyoti — APPROVED** [review]

**Comment by Judithlourde** [comment]
Hi Swathy! @swathivt 
Thank you for your feedback! I’ve made the changes you mentioned. Please review them and let me know if further adjustments are needed.

**Note:** I also made some backend changes, so make sure to pull the latest changes from the backend branch: fix/99/edit-kids-profile.

**Review by Alaleh-kash — APPROVED** [review]

**Review by swathivt — APPROVED** [review]
Great job Judith

**Review by JULIERAJ — CHANGES_REQUESTED** [review]
Hi @Judithlourde , thanks for this. Please try to resolve the vulnerabilities. We want to make sure to submit strong code with no vulnerabilities. I had these results after running command "npm i"
Screen Shot 2024-12-09 at 12 26 22 PM

**Comment by JULIERAJ** [comment]
> Hi @Judithlourde , thanks for this. Please try to resolve the vulnerabilities. We want to make sure to submit strong code with no vulnerabilities. I had these results after running command "npm i" Screen Shot 2024-12-09 at 12 26 22 PM

Or maybe it's from somewhere else, in the code that is holding these vulnerabilities?

**Comment by Judithlourde** [comment]
Hi Victoria @JULIERAJ,
Thanks for the feedback! I’ve resolved the vulnerabilities and got some help from [this GitHub issue](https://github.com/facebook/create-react-app/issues/13364). Let me know if you notice anything else!

**Review by JULIERAJ — APPROVED** [review]

**Pull request merged**
